# Generated by Django 3.2.4 on 2021-07-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=33)),
                ('nonce', models.CharField(max_length=33)),
                ('assoc', models.CharField(default='NONE', max_length=128)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16)),
                ('mac', models.CharField(max_length=13)),
                ('mq135', models.CharField(default='NONE', max_length=128)),
                ('sds011', models.CharField(default='NONE', max_length=128)),
                ('ordate', models.DateTimeField(editable=False)),
                ('redate', models.DateTimeField(editable=False)),
            ],
        ),
    ]
